title: My awesome blog from GitHub Learning Lab
author: Rene Bentes Pinto
email: renebentes@yahoo.com.br
description: > # this means to ignore newlines until "baseurl:"
  This site is a part of GitHub Learning Lab content.

# social links
twitter_username: renebentes # DO NOT include the @ character, or else the build will fail!
github_username:  renebentes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
